const {chromium}=require('C:/Users/39015/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
(async()=>{
 const root=path.resolve(__dirname,'../_site');let server;
 const prefix='/xiamen-gaoqi-t4-model/';
 if(!process.env.T4_SITE_URL){server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(prefix.length);if(!rel)rel='index.html';let file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary'})[ext]||'text/plain');res.end(data);});});await new Promise(r=>server.listen(8779,'127.0.0.1',r));}
 const base=process.env.T4_SITE_URL||'http://127.0.0.1:8779'+prefix;
 const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 try{await p.goto(base);await p.waitForFunction(()=>window.modelReady&&window.routesReady,null,{timeout:120000});await p.selectOption('#view','hall');await p.selectOption('#gate','73');for(const name of ['compare.html','arrival-finger-compare.html']){await p.goto(base+name);await p.waitForFunction(()=>[...document.images].every(x=>x.complete&&x.naturalWidth>0));}
 const r=await p.request.get(base+'assets/xiamen-gaoqi-t4.glb');const sha=crypto.createHash('sha256').update(await r.body()).digest('hex');const expected=fs.readFileSync(path.resolve(__dirname,'../SHA256SUMS.txt'),'utf8').split(/\s/)[0];if(sha!==expected)throw Error('Download checksum mismatch');if(errors.length)throw Error(errors.join('\n'));const report={base,sha256:sha,model:true,comparisons:true,errors,checkedAt:new Date().toISOString()};fs.writeFileSync(path.join(__dirname,process.env.T4_SITE_URL?'pages-validation.json':'staged-site-validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await b.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
